apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.services.admin.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deploymentStrategy.maxUnavailable }}
      maxSurge: {{ .Values.deploymentStrategy.maxSurge }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.services.admin.image }}:{{ .Values.services.admin.tag }}"
          ports:
            - containerPort: {{ .Values.services.admin.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: ADMIN_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: MONGO_URI
            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: CLIENT_URLS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: JWT_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_S3_BUCKET
          readinessProbe:
            tcpSocket:
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - port: {{ .Values.services.admin.port }}
      targetPort: {{ .Values.services.admin.port }}