{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "streamingapp-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ if .Values.secret.awsAccessKeyId }}{{ .Values.secret.awsAccessKeyId | quote }}{{ else if $existingSecret }}{{ index $existingSecret.data "AWS_ACCESS_KEY_ID" | b64dec | quote }}{{ else }}""{{ end }}
  AWS_SECRET_ACCESS_KEY: {{ if .Values.secret.awsSecretAccessKey }}{{ .Values.secret.awsSecretAccessKey | quote }}{{ else if $existingSecret }}{{ index $existingSecret.data "AWS_SECRET_ACCESS_KEY" | b64dec | quote }}{{ else }}""{{ end }}
  AWS_S3_BUCKET: {{ if .Values.secret.awsS3Bucket }}{{ .Values.secret.awsS3Bucket | quote }}{{ else if $existingSecret }}{{ index $existingSecret.data "AWS_S3_BUCKET" | b64dec | quote }}{{ else }}""{{ end }}