apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: streamingapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: sacdew77/streaming-admin:1.0.0
          ports:
            - containerPort: 3003
              name: http
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/streamingapp"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: JWT_SECRET
            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: CLIENT_URLS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secret
                  key: AWS_S3_BUCKET
            - name: AWS_CDN_URL
              value: ""
          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: streamingapp
spec:
  selector:
    app: admin
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  type: ClusterIP