apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
  namespace: streamingapp
type: Opaque
stringData:
  JWT_SECRET: "changeme"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_S3_BUCKET: ""